// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM_Vyx8UBKu7aWG73zgz2sCYuckCCO9Wo',
    appId: '1:795829679886:web:ce0d4e28eb4ca7b582495f',
    messagingSenderId: '795829679886',
    projectId: 'chitto-tech-3ecf9',
    authDomain: 'chitto-tech-3ecf9.firebaseapp.com',
    storageBucket: 'chitto-tech-3ecf9.firebasestorage.app',
    measurementId: 'G-BSTXSJLWX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_KfFqRcl5xK4amh3YTqEIXV3TyF5qS0',
    appId: '1:795829679886:android:170a8b233d3d4f0d82495f',
    messagingSenderId: '795829679886',
    projectId: 'chitto-tech-3ecf9',
    storageBucket: 'chitto-tech-3ecf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulL1moKWXU9ZJ403d4NGQ2kIYHnM0oyE',
    appId: '1:795829679886:ios:3884e22ee587834682495f',
    messagingSenderId: '795829679886',
    projectId: 'chitto-tech-3ecf9',
    storageBucket: 'chitto-tech-3ecf9.firebasestorage.app',
    iosBundleId: 'com.example.chitooTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulL1moKWXU9ZJ403d4NGQ2kIYHnM0oyE',
    appId: '1:795829679886:ios:3884e22ee587834682495f',
    messagingSenderId: '795829679886',
    projectId: 'chitto-tech-3ecf9',
    storageBucket: 'chitto-tech-3ecf9.firebasestorage.app',
    iosBundleId: 'com.example.chitooTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM_Vyx8UBKu7aWG73zgz2sCYuckCCO9Wo',
    appId: '1:795829679886:web:89ab90f6a54e4a5d82495f',
    messagingSenderId: '795829679886',
    projectId: 'chitto-tech-3ecf9',
    authDomain: 'chitto-tech-3ecf9.firebaseapp.com',
    storageBucket: 'chitto-tech-3ecf9.firebasestorage.app',
    measurementId: 'G-WM4TXC2X7H',
  );

}